In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2,3), np.int8)

In [18]:
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [19]:
ones.dtype

dtype('int8')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)

In [24]:
range_array

array([0, 2, 4, 6, 8])

In [25]:
# randint
random_array = np.random.randint(0, 10, size=(3,5))

In [26]:
random_array

array([[9, 3, 8, 9, 5],
       [7, 5, 6, 1, 8],
       [3, 6, 8, 1, 2]])

In [27]:
random_array.size

15

In [28]:
# random.random
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.60395275, 0.123189  , 0.12648491],
       [0.07971888, 0.27816568, 0.68272694],
       [0.70854185, 0.53008423, 0.4908301 ],
       [0.45038432, 0.6085648 , 0.60761653],
       [0.52659724, 0.4714979 , 0.71228413]])

In [29]:
# random.rand
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.43920154, 0.06438702, 0.70680956],
       [0.33815526, 0.44020087, 0.85370152],
       [0.66512691, 0.71092402, 0.90139613],
       [0.87506241, 0.57587625, 0.09523289],
       [0.81713267, 0.83597941, 0.29958216]])

In [30]:
# Psuedo-random numbers
np.random.seed(0)

random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])